### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [bennyty/CSCI-1010-Mentoring#1]
Hey bennyty!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by bennyty** [comment]
Hello bot, I don't believe that this is an infringement on integrity policies. The materials are my own, I developed them for the class and they were shared to all involved. I suppose if any of the business majors can decompile the exes then they could figure out the answers.
